# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'tawanda23/my-app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'


- task: Kubernetes@1
  displayName: 'Deploy to AKS'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'AKS DevOps'  
    namespace: 'Devops AKS'  
    command: 'apply'
    useConfigurationFile: true
    configurationType: 'filePath'
    filePath: '**/aks-terraform/application-manifest.yaml'  
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    containerRegistry: 'Docker Hub'
    dockerRegistryEndpoint: 'Docker Hub'