# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  containerName: 'my-app'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'tawanda23/my-app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    command: 'login'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    command: 'pull'
    repository: 'tawanda23/my-app'
    tags: 'latest'
