# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: 'latest, $(Build.BuildId)'

- script: |
    docker pull docker.io/tawanda23/my-app:latest

    docker run -d -p 50001:5000 --name my-app-container docker.io/tawanda23/my-app:latest

    sleep 10 #waits for container to start

    curl http://localhost:5001

    docker stop my-app-container
    docker rm my-app-container
  displayName: 'Test Docker Image'